services:
  cadvisor:
      image: gcr.io/cadvisor/cadvisor:latest
      hostname: cadvisor
      container_name: cadvisor
      restart: unless-stopped
      volumes:
        - "/:/rootfs:rw"
        - "/var/run:/var/run:ro"
        - "/sys:/sys:ro"
        - /var/run/docker.sock:/var/run/docker.sock:rw
        - "/dev/disk/:/dev/disk:ro"
      networks:
        - monitor-net
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /Users/serveruser/Monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /Users/serveruser/Monitoring/prometheus/:/prometheus
    networks:
      - monitor-net
    ports:
      - "9991:9090"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    container_name: grafana
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      #- ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - /Users/serveruser/Monitoring/grafana:/var/lib/grafana
    networks:
      - monitor-net
    ports:
      - "9992:3000"
networks:
  monitor-net:
    driver: bridge