# my global config
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080', 'host.docker.internal:9100']